"""CV Agent state — the data that flows between graph nodes."""

from typing import TypedDict


class CVAgentState(TypedDict):
    # Input
    user_request: str                # What the user asked for

    # Search
    search_queries: list[str]        # Queries generated by router
    chunks: list[dict]               # Retrieved chunks (text + metadata, no embeddings)
    min_score: float                 # Minimum similarity score to keep a chunk

    # Generation
    draft: str                       # First draft from GPT
    verified_output: str             # After fact-checking against chunks

    # Control
    iteration: int                   # How many retrieve→evaluate cycles so far
    max_iterations: int              # Safety limit (default 3)
    needs_more_data: bool            # Evaluate node sets this if chunks insufficient
    done: bool                       # True when pipeline complete
